repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-builtin-literals
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: flakehell
        name: flakehell
        entry: flakehell
        args: [lint]
        language: python
        types: [python]
